# Generated by Django 5.2.6 on 2025-10-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0005_alter_musica_options_alter_musica_duracao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Ex: 'Novidades do Rock Progressivo'", max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Uma breve descrição sobre esta coleção de álbuns.', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('albums', models.ManyToManyField(related_name='anuncios', to='album.album')),
            ],
            options={
                'verbose_name': 'Anúncio',
                'verbose_name_plural': 'Anúncios',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
