OPCOES_GENERO = (
    (1, 'Pop'),
    (2, 'Rock'),
    (3, 'Jazz'),
    (4, 'Clássica'),
    (5, 'Hip Hop'),
    (6, 'Eletrônica'),
    (7, 'Country'),
    (8, 'Reggae'),
    (9, 'Blues'),
    (10, 'Funk'),
    (11, 'Samba'),
    (12, 'MPB'), 
    (13, 'Forró'),
    (14, 'Axé'),
    (15, 'Gospel'),
    (16, 'Sertanejo'),
    (17, 'Indie'),
    (18, 'Metal'),
    (19, 'Punk'),
    (20, 'R&B'),
    (21, 'Disco'),
    (22, 'Folk'),
    (23, 'New Age'),
    (24, 'Clube'),
    (25, 'Eletro-Funk'),
)
OPCOES_ALBUM = (
    (1, 'Single'),
    (2, 'EP'),
    (3, 'Álbum Completo'),
)
OPCOES_FORMATO = (
    (1, 'CD'),
    (2, 'Vinil'),
    (3, 'Digital'),
    (4, 'Fita Cassete'),
) 
OPCOES_IDIOMA = (
    (1, 'Português'),
    (2, 'Inglês'),
    (3, 'Espanhol'),
    (4, 'Francês'),
    (5, 'Alemão'),
    (6, 'Italiano'),
    (7, 'Japonês'),
    (8, 'Chinês'),
    (9, 'Coreano'),
    (10, 'Outro'),
)