# Generated by Django 5.2.6 on 2025-10-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[(1, 'Pop'), (2, 'Rock'), (3, 'Jazz'), (4, 'Clássica'), (5, 'Hip Hop'), (6, 'Eletrônica'), (7, 'Country'), (8, 'Reggae'), (9, 'Blues'), (10, 'Funk'), (11, 'Samba'), (12, 'MPB'), (13, 'Forró'), (14, 'Axé'), (15, 'Gospel'), (16, 'Sertanejo'), (17, 'Indie'), (18, 'Metal'), (19, 'Punk'), (20, 'R&B'), (21, 'Disco'), (22, 'Folk'), (23, 'New Age'), (24, 'Clube'), (25, 'Eletro-Funk')], max_length=50)),
                ('ano_lancamento', models.IntegerField()),
                ('artista', models.CharField(max_length=100)),
                ('tipo_album', models.CharField(choices=[(1, 'Single'), (2, 'EP'), (3, 'Álbum Completo')], max_length=20)),
                ('formato', models.CharField(choices=[(1, 'CD'), (2, 'Vinil'), (3, 'Digital'), (4, 'Fita Cassete')], max_length=20)),
                ('idioma', models.CharField(choices=[(1, 'Português'), (2, 'Inglês'), (3, 'Espanhol'), (4, 'Francês'), (5, 'Alemão'), (6, 'Italiano'), (7, 'Japonês'), (8, 'Chinês'), (9, 'Coreano'), (10, 'Outro')], max_length=20)),
                ('duracao', models.DurationField()),
                ('musicas', models.CharField(max_length=500)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='album/fotos')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
