# Generated by Django 5.2.6 on 2025-10-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='capa',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='valor',
            new_name='preco',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.AlterField(
            model_name='album',
            name='formato',
            field=models.IntegerField(choices=[(1, 'CD'), (2, 'Vinil'), (3, 'Digital'), (4, 'Fita Cassete')]),
        ),
        migrations.AlterField(
            model_name='album',
            name='genero',
            field=models.IntegerField(choices=[(1, 'Pop'), (2, 'Rock'), (3, 'Jazz'), (4, 'Clássica'), (5, 'Hip Hop'), (6, 'Eletrônica'), (7, 'Country'), (8, 'Reggae'), (9, 'Blues'), (10, 'Funk'), (11, 'Samba'), (12, 'MPB'), (13, 'Forró'), (14, 'Axé'), (15, 'Gospel'), (16, 'Sertanejo'), (17, 'Indie'), (18, 'Metal'), (19, 'Punk'), (20, 'R&B'), (21, 'Disco'), (22, 'Folk'), (23, 'New Age'), (24, 'Clube'), (25, 'Eletro-Funk')]),
        ),
        migrations.AlterField(
            model_name='album',
            name='idioma',
            field=models.IntegerField(choices=[(1, 'Português'), (2, 'Inglês'), (3, 'Espanhol'), (4, 'Francês'), (5, 'Alemão'), (6, 'Italiano'), (7, 'Japonês'), (8, 'Chinês'), (9, 'Coreano'), (10, 'Outro')]),
        ),
        migrations.AlterField(
            model_name='album',
            name='tipo_album',
            field=models.IntegerField(choices=[(1, 'Single'), (2, 'EP'), (3, 'Álbum Completo')]),
        ),
    ]
