# Generated by Django 5.2.6 on 2025-10-16 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_rename_capa_album_foto_rename_valor_album_preco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='duracao',
        ),
        migrations.RemoveField(
            model_name='album',
            name='musicas',
        ),
        migrations.AddField(
            model_name='album',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Faixa')),
                ('duracao', models.DurationField(help_text='Formato: HH:MM:SS')),
                ('numero_faixa', models.PositiveIntegerField(verbose_name='Nº da Faixa')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicas', to='album.album')),
            ],
            options={
                'ordering': ['numero_faixa'],
                'unique_together': {('album', 'numero_faixa')},
            },
        ),
    ]
