# Generated by Django 5.2.6 on 2025-10-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_remove_album_duracao_remove_album_musicas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musica',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='musica',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='musica',
            name='duracao',
            field=models.CharField(max_length=5, verbose_name='Duração (MM:SS)'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.RemoveField(
            model_name='musica',
            name='numero_faixa',
        ),
    ]
