# Generated by Django 5.2.6 on 2025-10-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_alter_musica_options_alter_musica_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musica',
            options={'verbose_name_plural': 'Musicas'},
        ),
        migrations.AlterField(
            model_name='musica',
            name='duracao',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='musica',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
