# Generated by Django 5.2.6 on 2025-09-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.SmallIntegerField(choices=[(1, 'Ford'), (2, 'Chevrolet'), (3, 'Toyota'), (4, 'Honda'), (5, 'Volkswagen'), (6, 'Nissan'), (7, 'Hyundai'), (8, 'Kia'), (9, 'Renault'), (10, 'Peugeot')])),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('cor', models.SmallIntegerField(choices=[(1, 'Vermelho'), (2, 'Azul'), (3, 'Verde'), (4, 'Preto'), (5, 'Branco'), (6, 'Cinza'), (7, 'Amarelo'), (8, 'Prata'), (9, 'Marrom'), (10, 'Laranja')])),
                ('combustivel', models.SmallIntegerField(choices=[(1, 'Gasolina'), (2, 'Álcool'), (3, 'Diesel'), (4, 'Flex'), (5, 'Elétrico')])),
            ],
        ),
    ]
